### ISSUE TITLE
Implement Title Bar

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#173] opened 2023-01-16 02:40 UTC
## Description
Implement the title bar from the new menu system designs:

https://xd.adobe.com/view/7ad47acc-6bee-4e7a-a904-c06629355c92-2f87/

Notes from design:

> 
> Screen 1 - Hover over 'untitled' at the top of the screen for the same 'edit text box' that appears on editable info pop outs on pins. Clicking on this should open the text box and you can resave as such. Clicking off the text box should save it.
> Clicking on the drop down to the right of it should open the drop down menu. (happy for this to actually be a hover behaviour, instead of a click)

## Acceptance Criteria
- Implementation as per design
- The case in which a user attempts to name a map with a name that already exists as one of their maps should be handled. Currently a user can name multiple maps by the same name and I am happy to keep this method of handling.
- If the user changes the name of a map this renames the existing map.
- If the user deletes the name and doesnt replace it with anything this just saves the map with a blank name. _@king-mob @rogup Is this technically possible? If not I think we should have an error saying 'title cannot be blank' and this might need some design._

**Comment by King-Mob** [comment] 2023-01-16 13:45
@lin-d-hop 
- Starting name is "Untitled Document" ? Does "Untitled Map" not make more sense?
- Database allows blank map names.

**Comment by lin-d-hop** [comment] 2023-01-16 20:31
@King-Mob Good point on screen sizes. I do think we want to be moving toward a fully responsive app so def one to start thinking about. 

![Screenshot from 2023-01-16 20-18-48](https://user-images.githubusercontent.com/8669848/212759681-5ca31469-9c4b-4384-88c2-a5b57abde598.png)

There are lots of obvious wins eg LX logo becomes just icon, search bar collapses to search icon, name drops to menu. 

@MelissaMc20 What do you think? Although it wasn't in the original spec it would be great to add mobile responsiveness to the nav system. Do you have space to create mobile designs specifically for the top bar and nav system? Since we don't have pressing client tasks at the moment I'd be keen to scope creep into this epic

**Comment by MelissaMc20** [comment] 2023-02-22 17:19
@lin-d-hop duplicate of 173? 

In any case I've responded on this one > https://github.com/DigitalCommons/land-explorer-front-end/issues/137#issuecomment-1440435448

**Closed** 2023-05-22 16:08 UTC
